DROP TABLE PRODUCT;

CREATE TABLE PRODUCT(
    PRODUCT_ID VARCHAR2(10) PRIMARY KEY,
    P_NAME VARCHAR2(30) NOT NULL,
    PRICE NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(50),
    STOCK NUMBER NOT NULL
);

INSERT INTO PRODUCT VALUES('nb_ss7', '»ï¼º³ëÆ®ºÏ', 1570000, '½Ã¸®Áî7', 10);
INSERT INTO PRODUCT VALUES('nb_amd4', '¸ÆºÏ¿¡¾î', 1200000, 'xcode4', 20);
INSERT INTO PRODUCT VALUES('pc_ibm', 'ibmPC', 750000, 'window8', 5);

COMMIT;