DROP TABLE MEMBER2;

CREATE TABLE MEMBER2(
    MEMID VARCHAR2(10) PRIMARY KEY,
    GRADE VARCHAR2(10) CHECK(GRADE IN ('Basic', 'Stand', 'Premium')),
    NICKNAME VARCHAR2(20) UNIQUE,
    SIGNUP_DATE DATE DEFAULT SYSDATE,
    POINT NUMBER
);

COMMIT;

SELECT * FROM MEMBER2;

INSERT INTO MEMBER2 VALUES('abc123', 'Basic', 'abcd', '2022-12-18', 1000);
rollback;

SELECT TO_DATE(TO_CHAR('22-12-18'), 'YYMMDD') FROM DUAL;
SELECT TO_DATE('22-12-18', 'yymmdd') from dual;
SELECT TO_DATE('2022-11-18', 'YYYYMMDD') FROM DUAL;
SELECT '2022-12-18' FROM DUAL;
SELECT TO_CHAR('2022-12-18', 'YYMMDD') FROM DUAL;

SELECT *
FROM MEMBER2
ORDER BY DECODE(GRADE, 'Basic', 1, 'Stand', 2, 'Premium', 3)
