DROP TABLE MEMBER2;

CREATE TABLE MEMBER2(
    MEMID VARCHAR2(10) PRIMARY KEY,
    GRADE VARCHAR2(10) CHECK(GRADE IN ('Basic', 'Stand', 'Premium')),
    NICKNAME VARCHAR2(20) UNIQUE,
    SIGNUP_DATE DATE DEFAULT SYSDATE,
    POINT NUMBER
);

COMMIT;

SELECT * FROM MEMBER2;


SELECT TO_DATE(TO_CHAR('2022-12-18'), 'YYMMDD') FROM DUAL;