DROP TABLE MEMBER2;

CREATE TABLE MEMBER2(
    MEMID VARCHAR2(10) PRIMARY KEY,
    GRADE VARCHAR2(10) CHECK(GRADE IN ('Basic', 'Standard', 'Premium')),
    NICKNAME VARCHAR2(20) UNIQUE,
    SIGNUP_DATE DATE DEFAULT SYSDATE,
    POINT NUMBER
);

COMMIT;